### ISSUE TITLE
Little typo in Software page.

### ISSUE THREAD

**Issue by adam0white** [bonigarcia/bonigarcia.github.io#2]
Direct reference: https://github.com/bonigarcia/bonigarcia.github.io/blob/2e2200d145f91845e936175b7373770742c0d0bf/software.html#L301
Line 301 under 'CodeURJC' section.
Typed as 'Reserach' , should be 'Research'.

**Comment by bonigarcia** [comment]
Thanks a lot for reporting. Fixed now.
